### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [26]:
vector = np.random.rand(10,1)
print('Vector:')
print(vector)
print('Dimension -', vector.shape)

Vector:
[[0.50231341]
 [0.93815155]
 [0.34918285]
 [0.80956025]
 [0.93459259]
 [0.87763877]
 [0.82950747]
 [0.80394992]
 [0.38243184]
 [0.69714211]]
Dimension - (10, 1)


In [27]:
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])
print ('Matrix:')
print(matrix)
print('dimension -', matrix.shape)

Matrix:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
dimension - (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [28]:
add_vector= vector + 10
np.round(add_vector, 2)

array([[10.5 ],
       [10.94],
       [10.35],
       [10.81],
       [10.93],
       [10.88],
       [10.83],
       [10.8 ],
       [10.38],
       [10.7 ]])

In [29]:
mult_matrix = 2 * matrix
print(mult_matrix)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [30]:
sqrd_vector = vector ** 2
np.round(sqrd_vector, 2)

array([[0.25],
       [0.88],
       [0.12],
       [0.66],
       [0.87],
       [0.77],
       [0.69],
       [0.65],
       [0.15],
       [0.49]])

In [31]:
sqrd_vector_2 = np.square(vector)
np.round(sqrd_vector_2, 2)

array([[0.25],
       [0.88],
       [0.12],
       [0.66],
       [0.87],
       [0.77],
       [0.69],
       [0.65],
       [0.15],
       [0.49]])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [32]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [33]:
result_matrix = np.dot(B, A)
result_matrix, result_matrix.shape

(array([[0.7281, 0.5202],
        [0.2034, 0.2846]]),
 (2, 2))

In [34]:
result_vector = np.dot(result_matrix, C)
result_vector, result_vector.shape

(array([[0.5202],
        [0.2846]]),
 (2, 1))

In [35]:
result = np.dot(result_matrix, D)
result, result.shape

(array([[0.5202, 0.7281],
        [0.2846, 0.2034]]),
 (2, 2))


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [36]:
T_result_matrix = result_matrix.T
T_result_matrix, T_result_matrix.shape

(array([[0.7281, 0.2034],
        [0.5202, 0.2846]]),
 (2, 2))

In [37]:
T_vector = vector.T
print(T_vector)
T_vector.shape

[[0.50231341 0.93815155 0.34918285 0.80956025 0.93459259 0.87763877
  0.82950747 0.80394992 0.38243184 0.69714211]]


(1, 10)

після транспонування вектор-стовпчик став вектор-рядок

In [38]:
column_vector = np.expand_dims(vector, 1)

print('expand dims vector:') 
print(column_vector)
print(column_vector.shape)

print('vector:')
print(vector)
print(vector.shape)


expand dims vector:
[[[0.50231341]]

 [[0.93815155]]

 [[0.34918285]]

 [[0.80956025]]

 [[0.93459259]]

 [[0.87763877]]

 [[0.82950747]]

 [[0.80394992]]

 [[0.38243184]]

 [[0.69714211]]]
(10, 1, 1)
vector:
[[0.50231341]
 [0.93815155]
 [0.34918285]
 [0.80956025]
 [0.93459259]
 [0.87763877]
 [0.82950747]
 [0.80394992]
 [0.38243184]
 [0.69714211]]
(10, 1)


вийшов стовпчиковий вектор column_vector

In [39]:
T_column_vector = column_vector.T
T_column_vector, T_column_vector.shape

(array([[[0.50231341, 0.93815155, 0.34918285, 0.80956025, 0.93459259,
          0.87763877, 0.82950747, 0.80394992, 0.38243184, 0.69714211]]]),
 (1, 1, 10))